name: CI-CD

on:
  workflow_dispatch:
    inputs:
      message:
        description: 'Add a message'
        required: false
        type: string
  push:
    branches:
      - main
      - alpha
    paths-ignore:
      - '.github/**'
      - '.husky/**'
      - '.vscode/**'
      - 'assets/**'
      - 'docs/**'
      - '*prettier*'
      - '.gitignore'
      - '.nvmrc'
      - '.yarnrc'
      - 'jest*'
      - 'lint-staged*'
      - 'stryker.conf.js'

permissions:
  actions: read
  checks: read
  contents: write
  deployments: read
  id-token: write
  issues: write
  discussions: none
  packages: write
  pages: read
  pull-requests: write
  repository-projects: none
  security-events: none
  statuses: write

jobs:
  build-test-pack:
    name: Build, Test and Pack
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - name: Lint
        run: yarn lint

      # - name: Prettier
      #   run: yarn prettier:check

      - name: Unit tests
        run: yarn test:unit

      - name: Package the extension with webpack
        run: yarn package

      - name: Prepare the release version and product
        id: prepare
        run: yarn ci
        env:
          VSCE_TARGET: universal
          # All tokens are required since semantic-release needs to validate them
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          ## TODO In case you want to publish to OpenVSX
          # OVSX_PAT: ${{ secrets.OVSX_PAT }}

      - uses: actions/upload-artifact@v3
        with:
          name: universal
          path: '*.vsix'

  release:
    name: Publish the VSIX
    runs-on: ubuntu-latest
    needs: build-test-pack
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - run: git pull

      - uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: yarn

      - name: Install packages
        run: yarn install --frozen-lockfile

      - uses: actions/download-artifact@v3

      - run: yarn cd
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          VSCE_PAT: ${{ secrets.VSCE_PAT }}
          ## TODO In case you want to publish to OpenVSX
          # OVSX_PAT: ${{ secrets.OVSX_PAT }}
