name: Dependabot Reviewer

on: pull_request_target

permissions:
  contents: write
  pull-requests: write

jobs:
  dependabot:
    runs-on: ubuntu-latest
    if: ${{ github.actor == 'dependabot[bot]' }}
    steps:
      - name: Approve a PR
        run: gh pr review "$PR_URL" --approve --body "I automatically approve this PR from dependabot"
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GH_AUTOAPPROVE_TOKEN}}
      - name: Enable auto-merge for Dependabot PRs
        run: gh pr merge "$PR_URL" --auto --squash
        env:
          PR_URL: ${{github.event.pull_request.html_url}}
          GITHUB_TOKEN: ${{secrets.GH_AUTOAPPROVE_TOKEN}}
